name: Deploy

on: push

jobs:
  build:
    name: Build and deploy the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install libraries
        run: npm ci
      - name: build application
        run: npm run build
      - name: deploy application
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
